### ISSUE TITLE
Allow adding to a specific note ID instead of just the last one added.

### ISSUE THREAD

**Issue by xyaman** [BrigadaSOS/Nadeshiko#34]
As the title suggests, allow the user to select a specific note ID as a new option in the UI.

![image](https://github.com/BrigadaSOS/NadeDB/assets/32078353/981e2593-96e0-406b-bd1b-9562d83823d8)
Add a new item here.

**Comment by Natsume-197** [comment]
It works. Pending adjustment to make the modal consistent with the current design. Once that's done, this case will be closed.

Thank you!
